# spring:
#   mail:
#     host: smtp.yandex.ru
#     port: 465
#     username: mubiwebsite@yandex.ru
#     password: 1421210Mubi
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
#           ssl:
#             enable: true

